[project]
name = "eagle-mcp-server"
version = "0.1.0"
description = "An MCP server for Eagle"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=0.14.1",
    "httpx>=0.28.1",
]
